### ISSUE TITLE
Loading 'magic value'

### ISSUE THREAD

**Issue by ephayes** [OpenITI/mARkdown_scheme#1]
I had editpad pro on my laptop and it was working fine with OpenITI. Now I have loaded them onto my desktop, but it does not seem to recognize the magic value yet. Any thoughts?

**Comment by maximromanov** [comment]
Two reasons I can think of (all from Brief descriptions at https://alraqmiyyat.github.io/mARkdown/):
1. Wrong magic value (should be `######OpenITI#`)
2. You have not installed the highlighting scheme properly: make sure to fully close EditPad Pro (`File > Exit`; clicking on `Close`/[X] is not enough) before you copy the scheme files.
